[project]
name = "nerf-umc203"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flax>=0.10.5",
    "gin-config>=0.5.0",
    "ipykernel>=6.29.5",
    "jax>=0.5.3",
    "jaxlib>=0.5.3",
    "scikit-image>=0.25.2",
]
